prostages_accueil:
    path: /
    controller: App\Controller\ProstagesController::index

prostages_entreprises:
    path: /entreprises
    controller: App\Controller\ProstagesController::entreprises

prostages_formations:
    path: /formations
    controller: App\Controller\ProstagesController::formations

prostages_stage:
    path: /stage/{id}
    controller: App\Controller\ProstagesController::stage

